import {
  faArrowLeft,
  faAsterisk,
  faBan,
  faBars,
  faBell,
  faBook,
  faCalendarAlt,
  faCheck,
  faCloud,
  faCogs,
  faDatabase,
  faEye,
  faFlag,
  faHeart,
  faHome,
  faList,
  faLock,
  faPencilAlt,
  faPlus,
  faRoad,
  faSave,
  faSearch,
  faSignOutAlt,
  faSignInAlt,
  faSort,
  faSortDown,
  faSortUp,
  faSync,
  faTachometerAlt,
  faTasks,
  faThList,
  faTimes,
  faTrashAlt,
  faUser,
  faUserPlus,
  faUsers,
  faUsersCog,
  faWrench,
  faEnvelope,
  faArrowRight,
  faTrash,
  faWallet,
  faDollarSign,
  faBagShopping,
  faBasketShopping,
  faDesktop,
  faPhone,
  // jhipster-needle-add-icon-import
} from '@fortawesome/free-solid-svg-icons';

import { faFacebook, faChrome, faGithub, faTwitter, faGoogle, faInstagram, faLinkedinIn } from '@fortawesome/free-brands-svg-icons';

export const fontAwesomeIcons = [
  faArrowLeft,
  faArrowRight,
  faAsterisk,
  faBan,
  faBars,
  faBell,
  faBook,
  faCalendarAlt,
  faCheck,
  faCloud,
  faCogs,
  faDatabase,
  faEye,
  faFlag,
  faHeart,
  faHome,
  faList,
  faLock,
  faPencilAlt,
  faPlus,
  faRoad,
  faSave,
  faSearch,
  faSignOutAlt,
  faSignInAlt,
  faSort,
  faSortDown,
  faSortUp,
  faSync,
  faTachometerAlt,
  faTasks,
  faThList,
  faTimes,
  faTrashAlt,
  faUser,
  faUserPlus,
  faUsers,
  faUsersCog,
  faWrench,
  faEnvelope,
  faLock,
  faUser,
  faTrash,
  faWallet,
  faDollarSign,
  faBagShopping,
  faBasketShopping,
  faUser,
  faDesktop,
  faPhone,
  // jhipster-needle-add-icon-import
];

export const fontAwesomeBrandIcons = [faTwitter, faFacebook, faChrome, faGithub, faGoogle, faInstagram, faLinkedinIn];
